XGBClassifier:
  n_estimators: 60
  learning_rate: 0.05
  max_depth: 4
  min_child_weight: 5
  subsample: 0.8
  colsample_bytree: 0.8
  gamma: 0.1
  reg_alpha: 0.1
  reg_lambda: 1.0
  scale_pos_weight: 5
  objective: "binary:logistic"
  eval_metric: "auc"
  random_state: 42